name: "GitHub Classroom Autograding Results handler"
description: "Integrate your CS class with GitHub using GitHub Classroom"
inputs:
  runners:
    description: 'Comma-separated list of step ids'
    required: true

runs:
  using: "node20"
  main: "dist/main.js"
